# QC.NotificationTemplates.psm1
# Responsibility: Subject/body template expansion for QC workflow notifications.

function _QCNT-IsBlank([object]$Value) {
    if ($null -eq $Value) { return $true }
    if ($Value -is [string]) { return [string]::IsNullOrWhiteSpace($Value) }
    return $false
}

function Expand-QCNotificationTemplate {
    <#
    .SYNOPSIS
    Replaces {token} placeholders in a notification template string.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Template,
        [Parameter(Mandatory)]
        [hashtable]$Tokens
    )

    if (_QCNT-IsBlank $Template) { return '' }
    $result = [string]$Template
    foreach ($key in @($Tokens.Keys)) {
        $placeholder = '{' + [string]$key + '}'
        $value = if ($null -eq $Tokens[$key]) { '' } else { [string]$Tokens[$key] }
        $result = $result.Replace($placeholder, $value)
    }
    return $result
}

function New-QCNotificationEmailBody {
    <#
    .SYNOPSIS
    Builds a plain-text email body from a notification event object.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [hashtable]$Event,
        [string]$Intro = 'A ProjectWise QC workflow state change requires your attention.'
    )

    $lines = @(
        $Intro,
        '',
        ('Project: {0}' -f $(if ($Event.project) { $Event.project } else { '(unknown)' })),
        ('Document: {0}' -f $(if ($Event.documentName) { $Event.documentName } else { '(unknown)' })),
        ('Path: {0}' -f $(if ($Event.documentPath) { $Event.documentPath } else { '(unknown)' })),
        ('Previous state: {0}' -f $(if ($Event.previousState) { $Event.previousState } else { '(none)' })),
        ('Current state: {0}' -f $(if ($Event.currentState) { $Event.currentState } else { '(unknown)' })),
        ('Event: {0}' -f $(if ($Event.eventType) { $Event.eventType } else { '(unknown)' })),
        ''
    )
    if (-not (_QCNT-IsBlank $Event.actionRequired)) {
        $lines += 'Action required:'
        $lines += [string]$Event.actionRequired
        $lines += ''
    }
    if ($Event.sourceJobId) {
        $lines += ('Source job: {0}' -f [string]$Event.sourceJobId)
    }
    $lines += ''
    $lines += 'This message was generated by the ProjectWise QC automation system.'
    return ($lines -join [Environment]::NewLine)
}

Export-ModuleMember -Function Expand-QCNotificationTemplate, New-QCNotificationEmailBody
